image:
  repository: ghcr.io/simintero/automation-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3017

replicaCount: 2

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

podAnnotations:
  sim.io/rls-context: "true"

env:
  OPA_URL: "http://opa.simintero.svc.cluster.local:8181"
