receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

  transform/scrub_phi:
    trace_statements:
      - context: span
        statements:
          - delete_key(attributes, "member_ref")
          - delete_key(attributes, "resolution")
          - delete_key(attributes, "description")
          - delete_key(attributes, "filing_body")
          - delete_key(attributes, "body_ref")
          - delete_key(attributes, "member_phi")
    log_statements:
      - context: log
        statements:
          - delete_key(attributes, "member_ref")
          - delete_key(attributes, "resolution")
          - delete_key(attributes, "description")
          - delete_key(attributes, "filing_body")
          - delete_key(attributes, "body_ref")
          - delete_key(attributes, "member_phi")

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform/scrub_phi, batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [transform/scrub_phi, batch]
      exporters: [loki]
  extensions: []
  telemetry:
    logs:
      level: warn
