packages:
  - "platform/libs/*"
  - "platform/libs/*/*"
  - "platform/services/*"
  - "modules/enstellar/*"
  - "modules/digicore/*"
  - "modules/revital/*"
  - "modules/qualitron/*"
  - "modules/search/*"
  - "modules/analytics/*"
  - "apps/web/*"
  - "integration/e2e"
  - "contracts"
