image:
  repository: ghcr.io/simintero/fhir-facade
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8081

replicaCount: 1

resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 1000m

podAnnotations:
  sim.io/rls-context: "true"

env:
  SERVER_PORT: "8081"
  INTAKE_SERVICE_URL: "http://enstellar-case.simintero.svc.cluster.local:3013"
