image:
  repository: ghcr.io/simintero/saas-admin
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 200m

podAnnotations:
  sim.io/rls-context: "true"
