// packages/design-system/src/tokens.ts
export const colors = {
  // Legacy aliases
  deepNavy:         '#131b2e',
  complianceGreen:  '#006c49',
  intelligenceBlue: '#3980f4',
  surface:          '#f7f9fb',
  surfaceLow:       '#f2f4f6',
  surfaceMid:       '#eceef0',
  surfaceHigh:      '#e6e8ea',
  surfaceHighest:   '#e0e3e5',
  surfaceCard:      '#ffffff',
  error:            '#ba1a1a',
  warning:          '#b5780e',
  success:          '#006c49',
  info:             '#3980f4',
  ink:              '#191c1e',
  inkMuted:         '#45464d',

  // Full Material-3 / Clinical Integrity Design System Palette
  'surface-dim': '#d8dadc',
  'surface-bright': '#f7f9fb',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#f2f4f6',
  'surface-container': '#eceef0',
  'surface-container-high': '#e6e8ea',
  'surface-container-highest': '#e0e3e5',
  'on-surface': '#191c1e',
  'on-surface-variant': '#45464d',
  'inverse-surface': '#2d3133',
  'inverse-on-surface': '#eff1f3',
  'outline': '#76777d',
  'outline-variant': '#c6c6cd',
  'surface-tint': '#565e74',
  'primary': '#000000',
  'on-primary': '#ffffff',
  'primary-container': '#131b2e',
  'on-primary-container': '#7c839b',
  'inverse-primary': '#bec6e0',
  'secondary': '#006c49',
  'on-secondary': '#ffffff',
  'secondary-container': '#6cf8bb',
  'on-secondary-container': '#00714d',
  'tertiary': '#000000',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#001a42',
  'on-tertiary-container': '#3980f4',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#93000a',
  'primary-fixed': '#dae2fd',
  'primary-fixed-dim': '#bec6e0',
  'on-primary-fixed': '#131b2e',
  'on-primary-fixed-variant': '#3f465c',
  'secondary-fixed': '#6ffbbe',
  'secondary-fixed-dim': '#4edea3',
  'on-secondary-fixed': '#002113',
  'on-secondary-fixed-variant': '#005236',
  'tertiary-fixed': '#d8e2ff',
  'tertiary-fixed-dim': '#adc6ff',
  'on-tertiary-fixed': '#001a42',
  'on-tertiary-fixed-variant': '#004395',
  'background': '#f7f9fb',
  'on-background': '#191c1e',
  'surface-variant': '#e0e3e5',
} as const

export const fonts = {
  primary: "'Inter', system-ui, -apple-system, sans-serif",
  mono:    "'JetBrains Mono', 'Fira Code', monospace",
} as const

export const radius = {
  sm:   '0.125rem',
  md:   '0.25rem',
  lg:   '0.5rem',
  xl:   '0.75rem',
  card: '0.5rem',
  full: '9999px',
} as const

export const shadows = {
  card:     '0px 4px 12px rgba(15, 23, 42, 0.05)',
  dropdown: '0px 8px 24px rgba(15, 23, 42, 0.12)',
} as const
