image:
  repository: ghcr.io/simintero/x12-translator
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8082

replicaCount: 1

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 768Mi
    cpu: 500m

podAnnotations:
  sim.io/rls-context: "true"

env:
  SERVER_PORT: "8082"
  POSTGRES_URL: "jdbc:postgresql://postgres.simintero.svc.cluster.local:5432/simintero"
